
File drivers/usb/cdns3/core.c:
297:	int cdns_hw_role_switch(struct cdns *);
427:	int cdns_init(struct cdns *);
497:	int cdns_remove(struct cdns *);
File drivers/usb/cdns3/drd.c:
106:	void cdns_clear_vbus(struct cdns *);
475:	int cdns_drd_exit(struct cdns *);
260:	void cdns_drd_gadget_off(struct cdns *);
228:	int cdns_drd_gadget_on(struct cdns *);
207:	void cdns_drd_host_off(struct cdns *);
178:	int cdns_drd_host_on(struct cdns *);
384:	int cdns_drd_init(struct cdns *);
309:	int cdns_drd_update_mode(struct cdns *);
86:	int cdns_get_id(struct cdns *);
96:	int cdns_get_vbus(struct cdns *);
142:	bool cdns_is_device(struct cdns *);
132:	bool cdns_is_host(struct cdns *);
484:	bool cdns_power_is_lost(struct cdns *);
119:	void cdns_set_vbus(struct cdns *);
File drivers/usb/cdns3/host.c:
127:	int cdns_host_init(struct cdns *);
File drivers/usb/common/common.c:
276:	enum usb_dr_mode of_usb_get_dr_mode_by_phy(struct device_node *, int);
328:	bool of_usb_host_tpl_support(struct device_node *);
342:	int of_usb_update_otg_caps(struct device_node *, struct usb_otg_caps *);
231:	unsigned int usb_decode_interval(const struct usb_endpoint_descriptor *, enum usb_device_speed);
34:	const char *usb_ep_type_string(int);
190:	enum usb_dr_mode usb_get_dr_mode(struct device *);
107:	enum usb_device_speed usb_get_maximum_speed(struct device *);
134:	enum usb_ssp_rate usb_get_maximum_ssp_rate(struct device *);
210:	enum usb_dr_mode usb_get_role_switch_default_mode(struct device *);
400:	struct device *usb_of_get_companion_dev(struct device *);
43:	const char *usb_otg_state_string(enum usb_otg_state);
91:	const char *usb_speed_string(enum usb_device_speed);
154:	const char *usb_state_string(enum usb_device_state);
File drivers/usb/common/ulpi.c:
153:	int __ulpi_register_driver(struct ulpi_driver *, struct module *);
23:	int ulpi_read(struct ulpi *, u8);
321:	struct ulpi *ulpi_register_interface(struct device *, const struct ulpi_ops *);
171:	void ulpi_unregister_driver(struct ulpi_driver *);
350:	void ulpi_unregister_interface(struct ulpi *);
29:	int ulpi_write(struct ulpi *, u8, u8);
File drivers/usb/core/buffer.c:
115:	void *hcd_buffer_alloc(struct usb_bus *, size_t, gfp_t, dma_addr_t *);
65:	int hcd_buffer_create(struct usb_hcd *);
97:	void hcd_buffer_destroy(struct usb_hcd *);
144:	void hcd_buffer_free(struct usb_bus *, size_t, void *, dma_addr_t);
33:	void usb_init_pool_max(void);
File drivers/usb/core/config.c:
825:	void usb_destroy_configuration(struct usb_device *);
978:	int usb_get_bos_descriptor(struct usb_device *);
861:	int usb_get_configuration(struct usb_device *);
959:	void usb_release_bos_descriptor(struct usb_device *);
484:	void usb_release_interface_cache(struct kref *);
File drivers/usb/core/devio.c:
2906:	void usb_devio_cleanup(void);
2880:	int usb_devio_init(void);
748:	void usbfs_notify_resume(struct usb_device *);
743:	void usbfs_notify_suspend(struct usb_device *);
File drivers/usb/core/driver.c:
1096:	void usb_deregister(struct usb_driver *);
1018:	void usb_deregister_device_driver(struct usb_device_driver *);
824:	const struct usb_device_id *usb_device_match_id(struct usb_device *, const struct usb_device_id *);
839:	bool usb_driver_applicable(struct usb_device *, struct usb_device_driver *);
535:	int usb_driver_claim_interface(struct usb_driver *, struct usb_interface *, void *);
609:	void usb_driver_release_interface(struct usb_driver *, struct usb_interface *);
1113:	void usb_forced_unbind_intf(struct usb_interface *);
638:	int usb_match_device(struct usb_device *, const struct usb_device_id *);
802:	const struct usb_device_id *usb_match_id(struct usb_interface *, const struct usb_device_id *);
709:	int usb_match_one_id(struct usb_interface *, const struct usb_device_id *);
674:	int usb_match_one_id_intf(struct usb_device *, struct usb_host_interface *, const struct usb_device_id *);
975:	int usb_register_device_driver(struct usb_device_driver *, struct module *);
1043:	int usb_register_driver(struct usb_driver *, struct module *, const char *);
114:	ssize_t usb_show_dynids(struct usb_dynids *, char *);
42:	ssize_t usb_store_new_id(struct usb_dynids *, const struct usb_device_id *, struct device_driver *, const char *, size_t);
1200:	void usb_unbind_and_rebind_marked_interfaces(struct usb_device *);
File drivers/usb/core/endpoint.c:
149:	int usb_create_ep_devs(struct device *, struct usb_host_endpoint *, struct usb_device *);
183:	void usb_remove_ep_devs(struct usb_host_endpoint *);
File drivers/usb/core/file.c:
230:	void usb_deregister_dev(struct usb_interface *, struct usb_class_driver *);
132:	void usb_major_cleanup(void);
120:	int usb_major_init(void);
156:	int usb_register_dev(struct usb_interface *, struct usb_class_driver *);
File drivers/usb/core/generic.c:
56:	int usb_choose_configuration(struct usb_device *);
253:	void usb_generic_driver_disconnect(struct usb_device *);
226:	int usb_generic_driver_probe(struct usb_device *);
File drivers/usb/core/hcd.c:
2567:	struct usb_hcd *__usb_create_hcd(const struct hc_driver *, struct device *, struct device *, const char *, struct usb_hcd *);
2811:	int usb_add_hcd(struct usb_hcd *, unsigned int, unsigned long);
2036:	int usb_alloc_streams(struct usb_interface *, struct usb_host_endpoint **, unsigned int, unsigned int, gfp_t);
1094:	long usb_calc_bus_time(int, int, int, int);
2668:	struct usb_hcd *usb_create_hcd(const struct hc_driver *, struct device *, const char *);
2645:	struct usb_hcd *usb_create_shared_hcd(const struct hc_driver *, struct device *, const char *, struct usb_hcd *);
2086:	int usb_free_streams(struct usb_interface *, struct usb_host_endpoint **, unsigned int, gfp_t);
2702:	struct usb_hcd *usb_get_hcd(struct usb_hcd *);
2515:	void usb_hc_died(struct usb_hcd *);
1862:	int usb_hcd_alloc_bandwidth(struct usb_device *, struct usb_host_config *, struct usb_host_interface *, struct usb_host_interface *);
1211:	int usb_hcd_check_unlink_urb(struct usb_hcd *, struct urb *, int);
1984:	void usb_hcd_disable_endpoint(struct usb_device *, struct usb_host_endpoint *);
1068:	void usb_hcd_end_port_resume(struct usb_bus *, int);
2725:	int usb_hcd_find_raw_port_number(struct usb_hcd *, int);
1783:	void usb_hcd_flush_endpoint(struct usb_device *, struct usb_host_endpoint *);
2129:	int usb_hcd_get_frame_number(struct usb_device *);
1744:	void usb_hcd_giveback_urb(struct usb_hcd *, struct urb *, int);
2474:	irqreturn_t usb_hcd_irq(int, void *);
2717:	int usb_hcd_is_primary_hcd(struct usb_hcd *);
1153:	int usb_hcd_link_urb_to_ep(struct usb_hcd *, struct urb *);
1407:	int usb_hcd_map_urb_for_dma(struct usb_hcd *, struct urb *, gfp_t);
3100:	void usb_hcd_platform_shutdown(struct platform_device *);
752:	void usb_hcd_poll_rh_status(struct usb_hcd *);
2003:	void usb_hcd_reset_endpoint(struct usb_device *, struct usb_host_endpoint *);
3112:	int usb_hcd_setup_local_mem(struct usb_hcd *, phys_addr_t, dma_addr_t, size_t);
1046:	void usb_hcd_start_port_resume(struct usb_bus *, int);
1529:	int usb_hcd_submit_urb(struct urb *, gfp_t);
2120:	void usb_hcd_synchronize_unlinks(struct usb_device *);
1611:	int usb_hcd_unlink_urb(struct urb *, int);
1244:	void usb_hcd_unlink_urb_from_ep(struct usb_hcd *, struct urb *);
1360:	void usb_hcd_unmap_urb_for_dma(struct usb_hcd *, struct urb *);
1332:	void usb_hcd_unmap_urb_setup_for_dma(struct usb_hcd *, struct urb *);
2710:	void usb_put_hcd(struct usb_hcd *);
3032:	void usb_remove_hcd(struct usb_hcd *);
File drivers/usb/core/hub.c:
4582:	int hub_port_debounce(struct usb_hub *, int, bool);
2644:	int usb_authorize_device(struct usb_device *);
431:	int usb_clear_port_feature(struct usb_device *, int, int);
2629:	int usb_deauthorize_device(struct usb_device *);
2011:	bool usb_device_is_owned(struct usb_device *);
148:	int usb_device_supports_lpm(struct usb_device *);
4485:	int usb_disable_lpm(struct usb_device *);
4503:	int usb_disable_ltm(struct usb_device *);
2208:	void usb_disconnect(struct usb_device **);
4491:	void usb_enable_lpm(struct usb_device *);
4509:	void usb_enable_ltm(struct usb_device *);
4625:	void usb_ep0_reinit(struct usb_device *);
6285:	void usb_hub_adjust_deviceremovable(struct usb_device *, struct usb_hub_descriptor *);
1966:	int usb_hub_claim_port(struct usb_device *, unsigned int, struct usb_dev_state *);
5918:	void usb_hub_cleanup(void);
869:	int usb_hub_clear_tt_buffer(struct urb *);
6274:	struct usb_device *usb_hub_find_child(struct usb_device *, int);
5893:	int usb_hub_init(void);
620:	int usb_hub_port_status(struct usb_hub *, int, u16 *, u16 *);
1998:	void usb_hub_release_all_ports(struct usb_device *, struct usb_dev_state *);
1982:	int usb_hub_release_port(struct usb_device *, unsigned int, struct usb_dev_state *);
835:	int usb_hub_set_port_power(struct usb_device *, struct usb_hub *, int, bool);
141:	struct usb_hub *usb_hub_to_struct_hub(struct usb_device *);
684:	void usb_kick_hub_wq(struct usb_device *);
2523:	int usb_new_device(struct usb_device *);
4560:	int usb_port_disable(struct usb_device *);
3130:	int usb_port_is_power_on(struct usb_hub *, unsigned int);
6254:	void usb_queue_reset_device(struct usb_interface *);
999:	int usb_remove_device(struct usb_device *);
6131:	int usb_reset_device(struct usb_device *);
2056:	void usb_set_device_state(struct usb_device *, enum usb_device_state);
4494:	int usb_unlocked_disable_lpm(struct usb_device *);
4500:	void usb_unlocked_enable_lpm(struct usb_device *);
700:	void usb_wakeup_notification(struct usb_device *, unsigned int);
File drivers/usb/core/message.c:
2285:	int cdc_parse_cdc_header(struct usb_cdc_parsed_header *, struct usb_interface *, u8 *, int);
1811:	void usb_authorize_interface(struct usb_interface *);
363:	int usb_bulk_msg(struct usb_device *, unsigned int, void *, int, int *, int);
1018:	char *usb_cache_string(struct usb_device *, int);
1209:	int usb_clear_halt(struct usb_device *, int);
136:	int usb_control_msg(struct usb_device *, unsigned int, __u8, __u8, __u16, __u16, void *, __u16, int);
263:	int usb_control_msg_recv(struct usb_device *, __u8, __u8, __u8, __u16, __u16, void *, __u16, int, gfp_t);
198:	int usb_control_msg_send(struct usb_device *, __u8, __u8, __u8, __u16, __u16, const void *, __u16, int, gfp_t);
1789:	void usb_deauthorize_interface(struct usb_interface *);
1394:	void usb_disable_device(struct usb_device *, int);
1284:	void usb_disable_endpoint(struct usb_device *, unsigned int, bool);
1343:	void usb_disable_interface(struct usb_device *, struct usb_interface *, bool);
2249:	int usb_driver_set_configuration(struct usb_device *, int);
1455:	void usb_enable_endpoint(struct usb_device *, struct usb_host_endpoint *, bool);
1479:	void usb_enable_interface(struct usb_device *, struct usb_interface *, bool);
780:	int usb_get_descriptor(struct usb_device *, unsigned char, unsigned char, void *, int);
1061:	int usb_get_device_descriptor(struct usb_device *, unsigned int);
1128:	int usb_get_status(struct usb_device *, int, int, int, void *);
324:	int usb_interrupt_msg(struct usb_device *, unsigned int, void *, int, int *, int);
1693:	int usb_reset_configuration(struct usb_device *);
1319:	void usb_reset_endpoint(struct usb_device *, unsigned int);
1958:	int usb_set_configuration(struct usb_device *, int);
1528:	int usb_set_interface(struct usb_device *, int, int);
1086:	int usb_set_isoch_delay(struct usb_device *);
720:	void usb_sg_cancel(struct usb_sg_request *);
501:	int usb_sg_init(struct usb_sg_request *, struct usb_device *, unsigned int, unsigned int, struct scatterlist *, int, size_t, gfp_t);
650:	void usb_sg_wait(struct usb_sg_request *);
967:	int usb_string(struct usb_device *, int, char *, size_t);
File drivers/usb/core/notify.c:
60:	void usb_notify_add_bus(struct usb_bus *);
49:	void usb_notify_add_device(struct usb_device *);
65:	void usb_notify_remove_bus(struct usb_bus *);
54:	void usb_notify_remove_device(struct usb_device *);
29:	void usb_register_notify(struct notifier_block *);
42:	void usb_unregister_notify(struct notifier_block *);
File drivers/usb/core/of.c:
25:	struct device_node *usb_of_get_device_node(struct usb_device *, int);
92:	struct device_node *usb_of_get_interface_node(struct usb_device *, u8, u8);
57:	bool usb_of_has_combined_node(struct usb_device *);
File drivers/usb/core/phy.c:
49:	struct usb_phy_roothub *usb_phy_roothub_alloc(struct device *);
154:	int usb_phy_roothub_calibrate(struct usb_phy_roothub *);
105:	int usb_phy_roothub_exit(struct usb_phy_roothub *);
78:	int usb_phy_roothub_init(struct usb_phy_roothub *);
202:	void usb_phy_roothub_power_off(struct usb_phy_roothub *);
175:	int usb_phy_roothub_power_on(struct usb_phy_roothub *);
227:	int usb_phy_roothub_resume(struct device *, struct usb_phy_roothub *);
126:	int usb_phy_roothub_set_mode(struct usb_phy_roothub *, enum phy_mode);
214:	int usb_phy_roothub_suspend(struct device *, struct usb_phy_roothub *);
File drivers/usb/core/port.c:
669:	int usb_hub_create_port_device(struct usb_hub *, int);
759:	void usb_hub_remove_port_device(struct usb_hub *, int);
File drivers/usb/core/quirks.c:
709:	void usb_detect_interface_quirks(struct usb_device *);
681:	void usb_detect_quirks(struct usb_device *);
579:	bool usb_endpoint_is_ignored(struct usb_device *, struct usb_host_interface *, struct usb_endpoint_descriptor *);
722:	void usb_release_quirk_list(void);
File drivers/usb/core/sysfs.c:
1021:	int usb_create_sysfs_dev_files(struct usb_device *);
1241:	void usb_create_sysfs_intf_files(struct usb_interface *);
1050:	void usb_remove_sysfs_dev_files(struct usb_device *);
1258:	void usb_remove_sysfs_intf_files(struct usb_interface *);
File drivers/usb/core/urb.c:
71:	struct urb *usb_alloc_urb(int, gfp_t);
1048:	int usb_anchor_empty(struct usb_anchor *);
953:	void usb_anchor_resume_wakeups(struct usb_anchor *);
939:	void usb_anchor_suspend_wakeups(struct usb_anchor *);
127:	void usb_anchor_urb(struct urb *, struct usb_anchor *);
803:	void usb_block_urb(struct urb *);
94:	void usb_free_urb(struct urb *);
993:	struct urb *usb_get_from_anchor(struct usb_anchor *);
111:	struct urb *usb_get_urb(struct urb *);
44:	void usb_init_urb(struct urb *);
823:	void usb_kill_anchored_urbs(struct usb_anchor *);
714:	void usb_kill_urb(struct urb *);
204:	int usb_pipe_type_check(struct usb_device *, unsigned int);
861:	void usb_poison_anchored_urbs(struct usb_anchor *);
761:	void usb_poison_urb(struct urb *);
1020:	void usb_scuttle_anchored_urbs(struct usb_anchor *);
368:	int usb_submit_urb(struct urb *, gfp_t);
165:	void usb_unanchor_urb(struct urb *);
920:	void usb_unlink_anchored_urbs(struct usb_anchor *);
675:	int usb_unlink_urb(struct urb *);
895:	void usb_unpoison_anchored_urbs(struct usb_anchor *);
782:	void usb_unpoison_urb(struct urb *);
225:	int usb_urb_ep_type_check(const struct urb *);
974:	int usb_wait_anchor_empty_timeout(struct usb_anchor *, unsigned int);
File drivers/usb/core/usb.c:
880:	int __usb_get_extra_descriptor(char *, unsigned int, unsigned char, void **, size_t);
932:	void *usb_alloc_coherent(struct usb_device *, size_t, gfp_t, dma_addr_t *);
574:	struct usb_device *usb_alloc_dev(struct usb_device *, struct usb_bus *, unsigned int);
307:	struct usb_host_interface *usb_altnum_to_altsetting(const struct usb_interface *, unsigned int);
58:	int usb_disabled(void);
220:	struct usb_host_interface *usb_find_alt_setting(struct usb_host_config *, unsigned int, unsigned int);
134:	int usb_find_common_endpoints(struct usb_host_interface *, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **);
180:	int usb_find_common_endpoints_reverse(struct usb_host_interface *, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **, struct usb_endpoint_descriptor **);
351:	struct usb_interface *usb_find_interface(struct usb_driver *, int);
393:	int usb_for_each_dev(void *, int (*)(struct usb_device *, void *));
952:	void usb_free_coherent(struct usb_device *, size_t, void *, dma_addr_t);
868:	int usb_get_current_frame_number(struct usb_device *);
698:	struct usb_device *usb_get_dev(struct usb_device *);
736:	struct usb_interface *usb_get_intf(struct usb_interface *);
271:	struct usb_interface *usb_ifnum_to_if(const struct usb_device *, unsigned int);
773:	struct device *usb_intf_get_dma_device(struct usb_interface *);
821:	int usb_lock_device_for_reset(struct usb_device *, const struct usb_interface *);
713:	void usb_put_dev(struct usb_device *);
752:	void usb_put_intf(struct usb_interface *);
File drivers/usb/host/xhci-dbg.c:
22:	void xhci_dbg_trace(struct xhci_hcd *, void (*)(struct va_format *), const char *, ...);
13:	char *xhci_get_slot_state(struct xhci_hcd *, struct xhci_container_ctx *);
File drivers/usb/host/xhci-debugfs.c:
443:	void xhci_debugfs_create_endpoint(struct xhci_hcd *, struct xhci_virt_device *, int);
716:	void xhci_debugfs_create_root(void);
591:	void xhci_debugfs_create_slot(struct xhci_hcd *, int);
566:	void xhci_debugfs_create_stream_files(struct xhci_hcd *, struct xhci_virt_device *, int);
704:	void xhci_debugfs_exit(struct xhci_hcd *);
652:	void xhci_debugfs_init(struct xhci_hcd *);
470:	void xhci_debugfs_remove_endpoint(struct xhci_hcd *, struct xhci_virt_device *, int);
721:	void xhci_debugfs_remove_root(void);
611:	void xhci_debugfs_remove_slot(struct xhci_hcd *, int);
File drivers/usb/host/xhci-ext-caps.c:
84:	int xhci_ext_cap_init(struct xhci_hcd *);
File drivers/usb/host/xhci-hub.c:
460:	int xhci_find_slot_id_by_port(struct usb_hcd *, struct xhci_hcd *, u16);
655:	struct xhci_hub *xhci_get_rhub(struct usb_hcd *);
1196:	int xhci_hub_control(struct usb_hcd *, u16, u16, u16, char *, u16);
1635:	int xhci_hub_status_data(struct usb_hcd *, char *);
444:	u32 xhci_port_state_to_neutral(u32);
562:	void xhci_ring_device(struct xhci_hcd *, int);
783:	void xhci_set_link_state(struct xhci_hcd *, struct xhci_port *, u32);
827:	void xhci_test_and_clear_bit(struct xhci_hcd *, struct xhci_port *, u32);
File drivers/usb/host/xhci-mem.c:
1733:	struct xhci_command *xhci_alloc_command(struct xhci_hcd *, bool, gfp_t);
1759:	struct xhci_command *xhci_alloc_command_with_ctx(struct xhci_hcd *, bool, gfp_t);
468:	struct xhci_container_ctx *xhci_alloc_container_ctx(struct xhci_hcd *, int, gfp_t);
1792:	int xhci_alloc_erst(struct xhci_hcd *, struct xhci_ring *, struct xhci_erst *, gfp_t);
603:	struct xhci_stream_info *xhci_alloc_stream_info(struct xhci_hcd *, unsigned int, unsigned int, unsigned int, gfp_t);
820:	int xhci_alloc_tt_info(struct xhci_hcd *, struct xhci_virt_device *, struct usb_device *, struct usb_tt *, gfp_t);
964:	int xhci_alloc_virt_device(struct xhci_hcd *, int, struct usb_device *, gfp_t);
1534:	void xhci_clear_endpoint_bw_info(struct xhci_bw_info *);
1037:	void xhci_copy_ep0_dequeue_into_input_ctx(struct xhci_hcd *, struct usb_device *);
584:	struct xhci_ring *xhci_dma_to_transfer_ring(struct xhci_virt_ep *, u64);
1602:	void xhci_endpoint_copy(struct xhci_hcd *, struct xhci_container_ctx *, struct xhci_container_ctx *, unsigned int);
1416:	int xhci_endpoint_init(struct xhci_hcd *, struct xhci_virt_device *, struct usb_device *, struct usb_host_endpoint *, gfp_t);
1515:	void xhci_endpoint_zero(struct xhci_hcd *, struct xhci_virt_device *, struct usb_host_endpoint *);
1783:	void xhci_free_command(struct xhci_hcd *, struct xhci_command *);
494:	void xhci_free_container_ctx(struct xhci_hcd *, struct xhci_container_ctx *);
411:	void xhci_free_endpoint_ring(struct xhci_hcd *, struct xhci_virt_device *, unsigned int);
1822:	void xhci_free_erst(struct xhci_hcd *, struct xhci_erst *);
758:	void xhci_free_stream_info(struct xhci_hcd *, struct xhci_stream_info *);
865:	void xhci_free_virt_device(struct xhci_hcd *, int);
522:	struct xhci_ep_ctx *xhci_get_ep_ctx(struct xhci_hcd *, struct xhci_container_ctx *, unsigned int);
503:	struct xhci_input_control_ctx *xhci_get_input_control_ctx(struct xhci_container_ctx *);
512:	struct xhci_slot_ctx *xhci_get_slot_ctx(struct xhci_hcd *, struct xhci_container_ctx *);
296:	void xhci_initialize_ring_info(struct xhci_ring *, unsigned int);
1835:	void xhci_mem_cleanup(struct xhci_hcd *);
2378:	int xhci_mem_init(struct xhci_hcd *, gfp_t);
371:	struct xhci_ring *xhci_ring_alloc(struct xhci_hcd *, unsigned int, unsigned int, enum xhci_ring_type, unsigned int, gfp_t);
423:	int xhci_ring_expansion(struct xhci_hcd *, struct xhci_ring *, unsigned int, gfp_t);
280:	void xhci_ring_free(struct xhci_hcd *, struct xhci_ring *);
1088:	int xhci_setup_addressable_virt_dev(struct xhci_hcd *, struct usb_device *);
745:	void xhci_setup_no_streams_ep_input_ctx(struct xhci_ep_ctx *, struct xhci_virt_ep *);
721:	void xhci_setup_streams_ep_input_ctx(struct xhci_hcd *, struct xhci_ep_ctx *, struct xhci_stream_info *);
1628:	void xhci_slot_copy(struct xhci_hcd *, struct xhci_container_ctx *, struct xhci_container_ctx *);
1544:	void xhci_update_bw_info(struct xhci_hcd *, struct xhci_container_ctx *, struct xhci_input_control_ctx *, struct xhci_virt_device *);
1778:	void xhci_urb_free_priv(struct urb_priv *);
File drivers/usb/host/xhci-ring.c:
3281:	unsigned int count_trbs(u64, u64);
158:	void inc_deq(struct xhci_hcd *, struct xhci_ring *);
2020:	struct xhci_segment *trb_in_td(struct xhci_hcd *, struct xhci_segment *, union xhci_trb *, union xhci_trb *, dma_addr_t, bool);
1555:	void xhci_cleanup_command_queue(struct xhci_hcd *);
1563:	void xhci_handle_command_timeout(struct work_struct *);
1220:	void xhci_hc_died(struct xhci_hcd *);
3015:	irqreturn_t xhci_irq(struct usb_hcd *);
2124:	int xhci_is_vendor_info_code(struct xhci_hcd *, unsigned int);
3103:	irqreturn_t xhci_msi_irq(int, void *);
4305:	int xhci_queue_address_device(struct xhci_hcd *, struct xhci_command *, dma_addr_t, u32, enum xhci_setup_dev);
3519:	int xhci_queue_bulk_tx(struct xhci_hcd *, gfp_t, struct urb *, int, unsigned int);
4330:	int xhci_queue_configure_endpoint(struct xhci_hcd *, struct xhci_command *, dma_addr_t, u32, bool);
3680:	int xhci_queue_ctrl_tx(struct xhci_hcd *, gfp_t, struct urb *, int, unsigned int);
4341:	int xhci_queue_evaluate_context(struct xhci_hcd *, struct xhci_command *, dma_addr_t, u32, bool);
3391:	int xhci_queue_intr_tx(struct xhci_hcd *, gfp_t, struct urb *, int, unsigned int);
4170:	int xhci_queue_isoc_tx_prepare(struct xhci_hcd *, gfp_t, struct urb *, int, unsigned int);
4321:	int xhci_queue_reset_device(struct xhci_hcd *, struct xhci_command *, u32);
4366:	int xhci_queue_reset_ep(struct xhci_hcd *, struct xhci_command *, int, unsigned int, enum xhci_ep_reset_type);
4297:	int xhci_queue_slot_control(struct xhci_hcd *, struct xhci_command *, u32, u32);
4354:	int xhci_queue_stop_endpoint(struct xhci_hcd *, struct xhci_command *, int, unsigned int, int);
4314:	int xhci_queue_vendor_command(struct xhci_hcd *, struct xhci_command *, u32, u32, u32, u32);
301:	void xhci_ring_cmd_db(struct xhci_hcd *);
478:	void xhci_ring_doorbell_for_active_rings(struct xhci_hcd *, unsigned int, unsigned int);
426:	void xhci_ring_ep_doorbell(struct xhci_hcd *, unsigned int, unsigned int, unsigned int);
69:	dma_addr_t xhci_trb_virt_to_dma(struct xhci_segment *, union xhci_trb *);
529:	struct xhci_ring *xhci_triad_to_transfer_ring(struct xhci_hcd *, unsigned int, unsigned int, unsigned int);
File drivers/usb/host/xhci.c:
2003:	int xhci_add_endpoint(struct usb_hcd *, struct usb_device *, struct usb_host_endpoint *);
4082:	int xhci_alloc_dev(struct usb_hcd *, struct usb_device *);
3039:	int xhci_check_bandwidth(struct usb_hcd *, struct usb_device *);
4011:	int xhci_disable_slot(struct xhci_hcd *, u32);
1920:	int xhci_drop_endpoint(struct usb_hcd *, struct usb_device *, struct usb_host_endpoint *);
4371:	int xhci_find_raw_port_number(struct usb_hcd *, int);
3770:	void xhci_free_device_endpoint_resources(struct xhci_hcd *, struct xhci_virt_device *, bool);
5295:	int xhci_gen_setup(struct usb_hcd *, xhci_get_quirks_t);
1477:	unsigned int xhci_get_endpoint_index(struct usb_endpoint_descriptor *);
110:	int xhci_halt(struct xhci_hcd *);
68:	int xhci_handshake(void *, u32, u32, u64);
5497:	void xhci_init_driver(struct hc_driver *, const struct xhci_driver_overrides *);
1514:	unsigned int xhci_last_valid_endpoint(u32);
86:	void xhci_quiesce(struct xhci_hcd *);
170:	int xhci_reset(struct xhci_hcd *, u64);
3138:	void xhci_reset_bandwidth(struct usb_hcd *, struct usb_device *);
662:	int xhci_run(struct usb_hcd *);
793:	void xhci_shutdown(struct usb_hcd *);
133:	int xhci_start(struct xhci_hcd *);
5135:	int xhci_update_hub_device(struct usb_hcd *, struct usb_device *, struct usb_tt *, gfp_t);
2806:	void xhci_update_tt_active_eps(struct xhci_hcd *, struct xhci_virt_device *, int);
File drivers/usb/phy/of.c:
28:	enum usb_phy_interface of_usb_get_phy_mode(struct device_node *);
File drivers/usb/phy/phy-generic.c:
135:	int usb_gen_phy_init(struct usb_phy *);
157:	void usb_gen_phy_shutdown(struct usb_phy *);
206:	int usb_phy_gen_create_phy(struct device *, struct usb_phy_generic *);
33:	struct platform_device *usb_phy_generic_register(void);
40:	void usb_phy_generic_unregister(struct platform_device *);
File drivers/usb/phy/phy-ulpi.c:
282:	struct usb_phy *devm_otg_ulpi_create(struct device *, struct usb_phy_io_ops *, unsigned int);
259:	struct usb_phy *otg_ulpi_create(struct usb_phy_io_ops *, unsigned int);
File drivers/usb/phy/phy.c:
464:	struct usb_phy *devm_usb_get_phy(struct device *, enum usb_phy_type);
535:	struct usb_phy *devm_usb_get_phy_by_node(struct device *, struct device_node *, struct notifier_block *);
594:	struct usb_phy *devm_usb_get_phy_by_phandle(struct device *, const char *, u8);
627:	void devm_usb_put_phy(struct device *, struct usb_phy *);
664:	int usb_add_phy(struct usb_phy *, enum usb_phy_type);
715:	int usb_add_phy_dev(struct usb_phy *);
493:	struct usb_phy *usb_get_phy(enum usb_phy_type);
280:	void usb_phy_get_charger_current(struct usb_phy *, unsigned int *, unsigned int *);
231:	void usb_phy_set_charger_current(struct usb_phy *, unsigned int);
317:	void usb_phy_set_charger_state(struct usb_phy *, enum usb_charger_state);
766:	void usb_phy_set_event(struct usb_phy *, unsigned long);
644:	void usb_put_phy(struct usb_phy *);
748:	void usb_remove_phy(struct usb_phy *);
File drivers/usb/roles/class.c:
149:	struct usb_role_switch *fwnode_usb_role_switch_get(struct fwnode_handle *);
220:	const char *usb_role_string(enum usb_role);
187:	struct usb_role_switch *usb_role_switch_find_by_fwnode(const struct fwnode_handle *);
126:	struct usb_role_switch *usb_role_switch_get(struct device *);
388:	void *usb_role_switch_get_drvdata(struct usb_role_switch *);
70:	enum usb_role usb_role_switch_get_role(struct usb_role_switch *);
170:	void usb_role_switch_put(struct usb_role_switch *);
318:	struct usb_role_switch *usb_role_switch_register(struct device *, const struct usb_role_switch_desc *);
378:	void usb_role_switch_set_drvdata(struct usb_role_switch *, void *);
42:	int usb_role_switch_set_role(struct usb_role_switch *, enum usb_role);
366:	void usb_role_switch_unregister(struct usb_role_switch *);
File drivers/usb/storage/initializers.c:
34:	int usb_stor_euscsi_init(struct us_data *);
84:	int usb_stor_huawei_e220_init(struct us_data *);
51:	int usb_stor_ucr61s2b_init(struct us_data *);
File drivers/usb/storage/option_ms.c:
125:	int option_ms_init(struct us_data *);
File drivers/usb/storage/protocol.c:
121:	unsigned int usb_stor_access_xfer_buf(unsigned char *, unsigned int, struct scsi_cmnd *, struct scatterlist **, unsigned int *, enum xfer_buf_dir);
45:	void usb_stor_pad12_command(struct scsi_cmnd *, struct us_data *);
169:	void usb_stor_set_xfer_buf(unsigned char *, unsigned int, struct scsi_cmnd *);
104:	void usb_stor_transparent_scsi_command(struct scsi_cmnd *, struct us_data *);
61:	void usb_stor_ufi_command(struct scsi_cmnd *, struct us_data *);
File drivers/usb/storage/scsiglue.c:
663:	void usb_stor_host_template_init(struct scsi_host_template *, const char *, struct module *);
500:	void usb_stor_report_bus_reset(struct us_data *);
483:	void usb_stor_report_device_reset(struct us_data *);
File drivers/usb/storage/sierra_ms.c:
127:	int sierra_ms_init(struct us_data *);
File drivers/usb/storage/transport.c:
1075:	int usb_stor_Bulk_max_lun(struct us_data *);
1413:	int usb_stor_Bulk_reset(struct us_data *);
1115:	int usb_stor_Bulk_transport(struct scsi_cmnd *, struct us_data *);
1398:	int usb_stor_CB_reset(struct us_data *);
957:	int usb_stor_CB_transport(struct scsi_cmnd *, struct us_data *);
466:	int usb_stor_bulk_srb(struct us_data *, unsigned int, struct scsi_cmnd *);
385:	int usb_stor_bulk_transfer_buf(struct us_data *, unsigned int, void *, unsigned int, unsigned int *);
488:	int usb_stor_bulk_transfer_sg(struct us_data *, unsigned int, void *, unsigned int, int, int *);
227:	int usb_stor_clear_halt(struct us_data *, unsigned int);
185:	int usb_stor_control_msg(struct us_data *, unsigned int, u8, u8, u16, u16, void *, u16, int);
322:	int usb_stor_ctrl_transfer(struct us_data *, unsigned int, u8, u8, u16, u16, void *, u16);
604:	void usb_stor_invoke_transport(struct scsi_cmnd *, struct us_data *);
1425:	int usb_stor_port_reset(struct us_data *);
933:	void usb_stor_stop_transport(struct us_data *);
File drivers/usb/storage/usb.c:
261:	void fill_inquiry_response(struct us_data *, unsigned char *, unsigned int);
475:	void usb_stor_adjust_quirks(struct usb_device *, unsigned long *);
1083:	void usb_stor_disconnect(struct usb_interface *);
235:	int usb_stor_post_reset(struct usb_interface *);
225:	int usb_stor_pre_reset(struct usb_interface *);
936:	int usb_stor_probe1(struct us_data **, struct usb_interface *, const struct usb_device_id *, const struct us_unusual_dev *, struct scsi_host_template *);
999:	int usb_stor_probe2(struct us_data *);
File drivers/usb/storage/usual-tables.c:
91:	int usb_usual_ignore_device(struct usb_interface *);
File drivers/usb/typec/bus.c:
246:	int __typec_altmode_register_driver(struct typec_altmode_driver *, struct module *);
157:	void typec_altmode_attention(struct typec_altmode *, u32);
97:	int typec_altmode_enter(struct typec_altmode *, u32 *);
128:	int typec_altmode_exit(struct typec_altmode *);
201:	const struct typec_altmode *typec_altmode_get_partner(struct typec_altmode *);
221:	struct typec_altmode *typec_altmode_get_plug(struct typec_altmode *, enum typec_plug_index);
57:	int typec_altmode_notify(struct typec_altmode *, unsigned long, void *);
239:	void typec_altmode_put_plug(struct typec_altmode *);
259:	void typec_altmode_unregister_driver(struct typec_altmode_driver *);
177:	int typec_altmode_vdm(struct typec_altmode *, const u32, const u32 *, int);
278:	struct typec_altmode *typec_match_altmode(struct typec_altmode **, size_t, u16, u8);
File drivers/usb/typec/class.c:
319:	struct typec_port *typec_altmode2port(struct typec_altmode *);
290:	void typec_altmode_update_active(struct typec_altmode *, bool);
1111:	struct typec_cable *typec_cable_get(struct typec_port *);
1139:	int typec_cable_is_active(struct typec_cable *);
1127:	void typec_cable_put(struct typec_cable *);
1152:	int typec_cable_set_identity(struct typec_cable *);
1905:	int typec_find_orientation(const char *);
1949:	int typec_find_port_data_role(const char *);
1920:	int typec_find_port_power_role(const char *);
1935:	int typec_find_power_role(const char *);
1890:	int typec_find_pwr_opmode(const char *);
2046:	void *typec_get_drvdata(struct typec_port *);
2052:	int typec_get_fw_cap(struct typec_capability *, struct fwnode_handle *);
2026:	int typec_get_negotiated_svdm_version(struct typec_port *);
1989:	enum typec_orientation typec_get_orientation(struct typec_port *);
803:	struct typec_altmode *typec_partner_register_altmode(struct typec_partner *, const struct typec_altmode_desc *);
691:	int typec_partner_set_identity(struct typec_partner *);
771:	int typec_partner_set_num_altmodes(struct typec_partner *, int);
709:	void typec_partner_set_pd_revision(struct typec_partner *, u16);
817:	void typec_partner_set_svdm_version(struct typec_partner *, enum usb_pd_svdm_ver);
736:	int typec_partner_set_usb_power_delivery(struct typec_partner *, struct usb_power_delivery *);
836:	struct usb_power_delivery *typec_partner_usb_power_delivery_register(struct typec_partner *, struct usb_power_delivery_desc *);
996:	struct typec_altmode *typec_plug_register_altmode(struct typec_plug *, const struct typec_altmode_desc *);
964:	int typec_plug_set_num_altmodes(struct typec_plug *, int);
2106:	struct typec_altmode *typec_port_register_altmode(struct typec_port *, const struct typec_altmode_desc *);
2126:	void typec_port_register_altmodes(struct typec_port *, const struct typec_altmode_ops *, void *, struct typec_altmode **, size_t);
1237:	int typec_port_set_usb_power_delivery(struct typec_port *, struct usb_power_delivery *);
1172:	struct typec_cable *typec_register_cable(struct typec_port *, struct typec_cable_desc *);
852:	struct typec_partner *typec_register_partner(struct typec_port *, struct typec_partner_desc *);
1014:	struct typec_plug *typec_register_plug(struct typec_cable *, struct typec_plug_desc *);
2189:	struct typec_port *typec_register_port(struct device *, const struct typec_capability *);
1786:	void typec_set_data_role(struct typec_port *, enum typec_data_role);
2003:	int typec_set_mode(struct typec_port *, int);
1966:	int typec_set_orientation(struct typec_port *, enum typec_orientation);
1855:	void typec_set_pwr_opmode(struct typec_port *, enum typec_pwr_opmode);
1815:	void typec_set_pwr_role(struct typec_port *, enum typec_role);
1834:	void typec_set_vconn_role(struct typec_port *, enum typec_role);
582:	void typec_unregister_altmode(struct typec_altmode *);
1217:	void typec_unregister_cable(struct typec_cable *);
900:	void typec_unregister_partner(struct typec_partner *);
1052:	void typec_unregister_plug(struct typec_plug *);
2309:	void typec_unregister_port(struct typec_port *);
File drivers/usb/typec/mux.c:
338:	struct typec_mux *fwnode_typec_mux_get(struct fwnode_handle *, const struct typec_altmode_desc *);
71:	struct typec_switch *fwnode_typec_switch_get(struct fwnode_handle *);
509:	void *typec_mux_get_drvdata(struct typec_mux_dev *);
394:	void typec_mux_put(struct typec_mux *);
453:	struct typec_mux_dev *typec_mux_register(struct device *, const struct typec_mux_desc *);
411:	int typec_mux_set(struct typec_mux *, struct typec_mux_state *);
503:	void typec_mux_set_drvdata(struct typec_mux_dev *, void *);
496:	void typec_mux_unregister(struct typec_mux_dev *);
244:	void *typec_switch_get_drvdata(struct typec_switch_dev *);
126:	void typec_switch_put(struct typec_switch *);
165:	struct typec_switch_dev *typec_switch_register(struct device *, const struct typec_switch_desc *);
203:	int typec_switch_set(struct typec_switch *, enum typec_orientation);
238:	void typec_switch_set_drvdata(struct typec_switch_dev *, void *);
231:	void typec_switch_unregister(struct typec_switch_dev *);
File drivers/usb/typec/pd.c:
704:	void usb_power_delivery_exit(void);
580:	struct usb_power_delivery *usb_power_delivery_find(const char *);
699:	int usb_power_delivery_init(void);
661:	int usb_power_delivery_link_device(struct usb_power_delivery *, struct device *);
606:	struct usb_power_delivery *usb_power_delivery_register(struct device *, struct usb_power_delivery_desc *);
476:	struct usb_power_delivery_capabilities *usb_power_delivery_register_capabilities(struct usb_power_delivery *, struct usb_power_delivery_capabilities_desc *);
686:	void usb_power_delivery_unlink_device(struct usb_power_delivery *, struct device *);
644:	void usb_power_delivery_unregister(struct usb_power_delivery *);
516:	void usb_power_delivery_unregister_capabilities(struct usb_power_delivery_capabilities *);
File drivers/usb/typec/retimer.c:
47:	struct typec_retimer *fwnode_typec_retimer_get(struct fwnode_handle *);
152:	void *typec_retimer_get_drvdata(struct typec_retimer *);
65:	void typec_retimer_put(struct typec_retimer *);
105:	struct typec_retimer *typec_retimer_register(struct device *, const struct typec_retimer_desc *);
74:	int typec_retimer_set(struct typec_retimer *, struct typec_retimer_state *);
145:	void typec_retimer_unregister(struct typec_retimer *);
File drivers/usb/typec/tcpm/tcpci.c:
48:	struct tcpm_port *tcpci_get_tcpm_port(struct tcpci *);
638:	irqreturn_t tcpci_irq(struct tcpci *);
750:	struct tcpci *tcpci_register_port(struct device *, struct tcpci_data *);
806:	void tcpci_unregister_port(struct tcpci *);
File drivers/usb/typec/tcpm/tcpm.c:
5434:	void tcpm_cc_change(struct tcpm_port *);
5452:	void tcpm_pd_hard_reset(struct tcpm_port *);
2976:	void tcpm_pd_receive(struct tcpm_port *, const struct pd_message *);
926:	void tcpm_pd_transmit_complete(struct tcpm_port *, enum tcpm_transmit_status);
6445:	struct tcpm_port *tcpm_register_port(struct device *, struct tcpc_dev *);
5461:	void tcpm_sink_frs(struct tcpm_port *);
5470:	void tcpm_sourcing_vbus(struct tcpm_port *);
5984:	void tcpm_tcpc_reset(struct tcpm_port *);
6555:	void tcpm_unregister_port(struct tcpm_port *);
5443:	void tcpm_vbus_change(struct tcpm_port *);
